#P01.txt is generated by running Generate_P01_table.R

dfP01<- read.table(file="P01.txt",header=T,
                   sep='\t',quote="",
                   stringsAsFactors=F,
                   na.strings="NA",
                   comment.char="",
                   fileEncoding="Windows-1252")

